### DISCUSSION TITLE
How to install reflex in editable mode?

### DISCUSSION THREAD

**Discussion by larsblumberg** [reflex-dev/reflex#5343] [Q&A] [answered]
Earlier versions (v0.6.x) allowed to install reflex in editable mode via

```
poetry add -vv --editable ./reflex
```

with reflex checked out in a corresponding local directory `./reflex`. That helped me tremendously learning about reflex internals and even patch a few methods like `BaseState._process_event` to hook into the event processing. It basically allowed me to inject an event middleware, pretty much like FastAPI or Flask allow for a request middleware.

Now when using more recent `v0.7.x` versions installing reflex in editable mode seems to run forever. It's stuck in step

```
[build:build] Building editable...
```

with 1 CPU core going into full exhaustion for a long period of time. I never had the patience so far to wait until it might actually succeed.

Is there a proven way to nowadays install reflex in editable (development) mode so that I can observe and modify its source code? Eventually being able to learn and debug reflex internals will also help me to make some contributions to reflex itself.

**Comment by larsblumberg** [comment]
Found a workaround for installing `reflex` in editable mode: I Install `reflex` as a regular pypi dependency (via poetry). Since I am running my app in a docker container, I simply mount the `./reflex/reflex` directory of the locally cloned reflex repo (cloned at `./reflex`) into `/usr/local/lib/python3.11/site-packages/reflex`. And together with `watchexec` I have the reflex app restart on any source changes to `reflex` module.

Relevant parts in `compose.yaml`:

```yaml
services:
  app:
    command: |
      watchexec
        --restart
        -w /usr/local/lib/python3.11/site-packages/reflex
        reflex run --loglevel debug
    volumes:
      - ./app:/app
      - ./bin/watchexec_2.1.2:/usr/local/bin/watchexec
      - ./reflex/reflex:/usr/local/lib/python3.11/site-packages/reflex
```

With `./reflex` being the clone (a git submodule) of the corresponding reflex version.
