### ISSUE TITLE
Fail to compile when upgrading from 0.3.2 to 0.3.3?

### ISSUE THREAD

**Issue by renato-farias** [reflex-dev/reflex#2186]
**Describe the bug**
App says it failed to compile after reflex version was upgraded.

**To Reproduce**
In the pyproject.toml update reflex to use the github 0.3.3 tag:
```toml
[tool.poetry.dependencies]
python = "^3.10"
reflex = { git = "https://github.com/reflex-dev/reflex", tag = "v0.3.3" }
```

update the poetry env:

`poetry update`

then, run the app:

`reflex run`

**Expected behavior**
Compile the pages that were being compiled by the previous version.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/2206761/7dee90c7-4e6a-4e8a-b95d-9c30242f12fe)

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 0.3.3
 - OS: MacOS
 - Browser (Optional):
 
**Additional context**
N/A
