### ISSUE TITLE
How can I set rx.Config to deploy self-hosting on Kubernetes (GKE)?

### ISSUE THREAD

**Issue by ppippi-dev** [reflex-dev/reflex#3252]
### Discussed in https://github.com/orgs/reflex-dev/discussions/3251

I'd appreciate some tips on this! Please feel free to advise me

<div type='discussions-op-text'>

<sup>Originally posted by **ppippi-dev** May  9, 2024</sup>
Hi, I have some questions.

I want to deploy my app on Kubernetes using self-hosting.

But I have some problems.

My problem is this:

When I set the ingress as blah.blah.com, the pod is okay, but I can't find the backend server. I receive this error message:

```
Cannot connect to server: timeout. Check if server is reachable at ws://blah.blah.com:8000/_event
```

It's not the situation that I expected, I expected to route to `http://localhost:8000/_event`

However, when I set the api_url value and ingress to "http://blah-api.blah.com", it works well.

Why does it route to ws://blah.blah.com:8000/_event when I set api_url to http://localhost:8000?

---

I attaching my kubernetes deployment's code and python reflex rxconfig code

```yaml
          env:
            - name: API_URL
              value: "http://localhost:8000"
            - name: DEPLOY_URL
              value: "http://localhost:3000"
          command: ["sh", "-c", "poetry run reflex run --env prod"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: api
              containerPort: 8000
              protocol: TCP
```

```python
config = rx.Config(
    app_name="blahblah",
    api_url=os.getenv("API_URL", 'http://localhost:8000'),
    deploy_url=os.getenv("DEPLOY_URL", 'http://localhost:3000'),
    backend_host=os.getenv("BACKEND_HOST", '0.0.0.0'),
)
```</div>
