### ISSUE TITLE
FRONTEND_PATH is not applied for assets URLs

### ISSUE THREAD

**Issue by juangon** [reflex-dev/reflex#4458]
**Describe the bug**
When using frontend_path parameter (in my case used as env variable), when referencing assets in /assets folder, frontend_path is not added, throwing 404 errors for those resources

**To Reproduce**
Execute reflex populating FRONTEND_PATH env variable. Add some assets in /assets folder and reference them as stated in documents (prefixing them with slash '/').

**Expected behavior**
Assets path should add FRONTEND_PATH to the referenced resources.

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:3.12
 - Reflex Version: 0.65
 - OS: Linux
 - Browser (Optional):
 
**Additional context**

**Comment by juangon** [comment]
In order to give more clues, this doesn't work in two parts:
* favicon (located in /assets)
* Resources referenced from css, like:
```css
@font-face {
    font-family: inetum;
    font-weight: bold;
    src: url("/fonts/Poppins-Bold.ttf") format("truetype");
}
```

In font case, unless I am prefixing the url with FRONTEND_PATH, it won't work.
