### ISSUE TITLE
Add codespell.yml for Code Spell Check at CI/CD

### ISSUE THREAD

**Issue by mmmcorpsvit** [reflex-dev/reflex#4554]
**.github\workflows\codespell.yml**

```yml
name: Codespell

on:
  push:
    branches: [main]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
```
in root of project:
add file **.codespellignore**  - there just list of ignored words
add to file **pyproject.toml**, section: **[tool.poetry.group.dev.dependencies]**
```ini
codespell="2.3.0"
```

and new section:
```ini
[tool.codespell]
skip = '.codespellignore,.git,*.pdf,*.svg,*.jpg,*.jpeg,*.json,*.png,*.drawio,./alembic,poetry.lock,./github/*.*,.env.prod,./tests/fixtures/*.sql,./sqlalchemy_filters/*.*,./core/users_/*.*,*.dump,.web/*.*'
#check-hidden=
#check-filenames=
builtin = 'clear,rare,informal,usage,code,names'
ignore-words = '.codespellignore'
```

now you code spell check every time
