### ISSUE TITLE
A lot of wrong typing hints?

### ISSUE THREAD

**Issue by larsblumberg** [reflex-dev/reflex#4999]
**Describe the bug**
Using a LSP server with a Reflex app gives a lot of typing errors although all code is correct.

**To Reproduce**
Enable a LSP such as [`pylsp-mypy`](https://pypi.org/project/pylsp-mypy/) in a Reflex project.

- Code/Link to Repo: n/a

**Expected behavior**
LSP does not show typing errors when Relfex is used correctly.

**Screenshots**

![Image](https://github.com/user-attachments/assets/9b37120a-f543-47bf-88a9-8c2d49363771)

**Specifics (please complete the following information):**

- Python Version: 3.11
- Reflex Version: 0.7.3
- OS: Pop_OS

**Additional context**

Using these LSP dependencies:

```toml
[tool.poetry.group.dev.dependencies]
pylsp-mypy = ">=0.7.0"
python-lsp-ruff = ">=2.2.2"
python-lsp-server = ">=1.12.2"
```
